name: vip-resp
main: out/release/lib/nvsr.js
version: 0.0.1
description: vip status check responser
author:
  name: q3boy
  email: q3boy1@gmail.com
engines:
  node: >=0.6.0
directories:
  lib: ./lib
  bin: ./bin
bin:
  nvsr: ./bin/vip
homepage: http://github.com/q3boy/vip-resp
repository:
  type: git
  url: git://github.com/q3boy/vip-resp
bugs:
  url: http://github.com/q3boy/vip-resp/issues
dependencies:
  options-stream: >= 0.0.4
devDependencies:
  jake-tools: >=0.0.10
  expect.js: >= 0.2.0
  jake: >= 0.5.0
  yamljs: >= 0.1.3
scripts:
  prepublish: make all
  postpublish: make clean
  test: make test
