name: vip-resp
main: out/release/lib/nvsr.js
version: 0.0.1
description: vip status check responser
author:
  name: q3boy
  email: q3boy1@gmail.com
engines:
  node: >=0.8.0
directories:
  lib: ./lib
  bin: ./bin
bin:
  nvsr: ./bin/vip
homepage: http://github.com/q3boy/vip-resp
repository:
  type: git
  url: git://github.com/q3boy/vip-resp
bugs:
  url: http://github.com/q3boy/vip-resp/issues
dependencies:
  options-stream: '*'
devDependencies:
  expect.js: '*'
  yamljs: '*'
  mocha: '*'
  coffee-script: '*'
  jscover: '*'
scripts:
  prepublish: make release
  postpublish: make clean
  test: make test-cov
